//CODE_CHANGES=getGitChanges()
pipeline {    
    agent any
    environment{//environment variables-defining in environment block
        NEW_VERSION='Jenkinsversion'//public value
        SERVER_CREDENTIALS=credentials('Cred-example')//secret value
       

    } 
    tools {
        terraform 'Terraform_1.10.3' // Ensure this matches the tool name configured in Jenkins
    }
    stages {
        stage('build') {
            steps {
                // Ensure Terraform is installed and check the version
                echo 'building' //if terraform is chosen as linux..sh,in windows…bat
                echo "building the version ${NEW_VERSION}"
            }
        }
        stage('Test') {
            when{
                expression{
                    BRANCH_NAME == 'jenkin1'// && CODE_CHANGES==True //when condition met,then only steps block executed
                }
            }
            steps {
                // Initialize Terraform
                echo 'testing in jenkin1'
            }
        }
        stage('Deploy') {
            steps {
                // Initialize Terraform
                echo 'deploying'
                echo 'deploying with ${SERVER_CREDENTIALS}'
                withCredentials([ //Object syntax in groovy,instead of defining credential in the block,can be used like this
                        usernamePassword(credentialsId: 'Cred-example', usernameVariable: USER, passwordVariable: PWD)
                ]){
                    sh "some script ${env.USER} ${env.PWD}"
                }

            }
        }
        
        
    }
}
